### ISSUE TITLE
model quantization experiments

### ISSUE THREAD

**Issue by ramcn** [HKU-BAL/Clair#52]
Hello,

I am planning to do some experiments with model quantization both by post-training and retraining approach. The end goal is to reduce the size of the model to fit on an accelerator with smaller on-chip memory.  Currently, the size of the model (checkpoint files) is around 15MB, and I think it can potentially come down by 4x by fixed-point representation quantization for example.

I was hoping to get some inputs to achieve this without impacting the accuracy of variant calling. Please let me know if you have any recommendations based on your expertise so far.

Thanks,
Ram

**Comment by aquaskyline** [comment]
Hi Ram, it's a nice idea but we haven't tried out ourselves. We tried using FP16 instead of FP32 but our model suffered from either non-converging or reduced accuracy problem. Usually, quantization or reduced precision work when the capacity of the network is not fully utilized. From our experiments, the network architecture of Clair has little redundancy. But without a fully interpretable model, we are not 100% sure on that. Please do let us know any exciting results from your side.

**Comment by ramcn** [comment]
Thanks for the insights. I will keep you posted about my experiments.
